### ISSUE TITLE
Enhancement - Add context

### ISSUE THREAD

**Issue by fastcodejava** [amida-tech/jsonapter#15]
Sometimes we have to add one or more fields that is some kind of time stamp, e.g. timestamp1, timestamp2, timestamp3. 
If we have a function _getCurrentTimestamp_ that generates this time stamp but each time it it is a different one.  Also it is a slow to call a function so many times.
Sometime we have to put something extra which is not part of the payload. 
We added that to the payload but this causes problems with logging the payload later on.

I propose a new key called **contextKey** like **dataKey**. 

We can add a parameter called context to the engine : j2j.run(myTemplate, data, context).

The value of it could be a _string_, _function_,  or a _map_ etc.

Here are more details: 
Initialize the engine as 

    var context`= {timestamp : getCurrentTimestamp()};

    j2j.run(myTemplate, data, context).

Later on in the template : 

    {
       content: {
           created : {contextKey: "timestamp"},
           updated : {contextKey: "timestamp"}
       }
     }   

Now both `created` and `updated` will have exact same value.

Please let me know if you have any questions or comments.

**Comment by jsachs** [comment]
I'll let @au2 or @austundag chime in here, but this seems fine to me. You're always free to submit a pull request.

**Comment by fastcodejava** [comment]
I didn't hear from let @au2 or @austundag.  Submitted a pull request. Changed context to params as context is already there. Thanks Sameer Siddiqui for good help.

**Comment by au2** [comment]
I accepted pull request in the morning but I realized the case that did not have a test (array param) had problems.  I put a fix and test for it and put a PR.  Please take a look and let me know if it is how you wanted it to work.  I also bumped lodash version.

**Comment by fastcodejava** [comment]
@au2 
I don't know how to use array param now, It is fine for now. 

Thanks,

**Comment by au2** [comment]
Fixed in 1685b505c7f9331dd522123c0da92f154167aa1f
