### ISSUE TITLE
Updating to latest Lodash- breaks because of change in methodName 

### ISSUE THREAD

**Issue by SameerSiddiqui** [amida-tech/jsonapter#17]
on line 89 !_.contains is no longer available with latest lodash version 4.15.0 . If you guys are planning to update to latest lodash. This method has been renamed to _.includes 

Not a deal breaker. But just FYI. 

Thanks,
Sameer

**Comment by au2** [comment]
Fixed in c794f94d2201c055eff77334fe8ae1ec08213b5c
