### ISSUE TITLE
Enhancement - pass params to the function with value

### ISSUE THREAD

**Issue by fastcodejava** [amida-tech/jsonapter#19]
Right now the function takes only the input value. We could also pass the params (we just added this feature recently) to the function as shown below:

    var params = {mask: true, maskCharacter: "#"};

    j2j.run(myTemplate, data, params).

with 

    var mask = function(input, params)  {
       return params.mask ?  params.maskCharacter : input;
    };

and 

    var data = {
          cardNumber: "1111222233334444",
          expiryDate: "11/2018",
          cardholderFirstName: "John",
          cardholderLastName: "Doe",
          cardholderZip: "11111"
    };

and the template :

    {
      content: {
         cardNumber: {dataKey: "cardNumber", value:mask},
         expiryDate: {dataKey: "expiryDate", value:mask},
         cardholderFirstName: {dataKey: "cardholderFirstName"},
         cardholderLastName: {dataKey: "cardholderLastName"},
         cardholderZip: {dataKey: "expiryDate", value:mask}
      }
   }   

will produce

    {
          cardNumber: "#",
          expiryDate: "#",
          cardholderFirstName: "John",
          cardholderLastName: "Doe",
          cardholderZip: "#"
    }

**Comment by au2** [comment]
done in ef2b08a3813d4520f3bc314c7fcc1e54e83aeb68
