### ISSUE TITLE
default value actionKey doesn't handle boolvalue.

### ISSUE THREAD

**Issue by SameerSiddiqui** [amida-tech/jsonapter#2]
Hello, There is a small update i recommend. As of now default cannot handle bool value of true or false.
 My use Case is:
Source: 
{
          "id": "1-BMM16E",   
          "oneTimePayment":true
 }
Destination: {
           "id": "1-BMM16E",   
          "oneTimePayment":true
}

if oneTimePayment key/value are not present in Source i still want the key to be present in the Destination Object with a false value. So i pass actionKey default:false- But the challenge is default is not designed to handle true/false-

I propose the following solution on line 190- If we check if the default is a bool OR a string. This way default can handle both strings and Bool.
fix:   if ((result === null) && (_.isBoolean(template.default) || template.default))

**Comment by jsachs** [comment]
@SameerSiddiqui check out PR #3. If it looks right I'll merge it tonight. Thanks for the input!

**Comment by jsachs** [comment]
v0.0.2 released.
