### ISSUE TITLE
Enhancement : Rename value attribute to template

### ISSUE THREAD

**Issue by fastcodejava** [amida-tech/jsonapter#23]
Right now the `value` attributed being overloaded for several things.
The value can be a `function` or can be a string or it can be a object. When it is an object it is being treated as the template. I propose to use the tag `template` in this case. 

When it is an object without `dataKey` we take it as literally.  If `dataKey` is present we use it for lookup as shown below: 

The template : 

    var template = {
        content: {
             title: { dataKey: "gender", value: {M: 'Mr', F: 'Ms' }},
             name : { dataKey: "name" }
        }
    }
  
    var input = {name: 'Joe', gender: 'M'}};
 
will produce

     {
          title: "Mr",
          name : "Joe"
     }

Let me know if you have any questions or comments.

**Comment by SameerSiddiqui** [comment]
Yeah, will make it clear.

**Comment by au2** [comment]
I think I agree however that will not be backward compatible and I do not want to break compatibility now.  Maybe we can add `template` as you suggested and add a new 'format` and use that as how you want `value` to behave and remove `value` from documentation.   Next release we can remove `value` completely.

**Comment by SameerSiddiqui** [comment]
@fastcodejava  leave value alone- and add a new key call template!.

**Comment by au2** [comment]
Fixed in a6b1cd298e47532efe8bfc841b58879a3d0ff089
