### ISSUE TITLE
paramskey fails-  if we don't provide it from the run method, but map it inside template-

### ISSUE THREAD

**Issue by SameerSiddiqui** [amida-tech/jsonapter#25]
The above useCase should be handled- "Circular" string gets mapped.

Thanks,
Sameer

**Comment by fastcodejava** [comment]
Can you give an example?

**Comment by SameerSiddiqui** [comment]
var input = `[
  {
    "myId": "sampleId"
    "roles": [
      "SAMPLE_ROLE"
    ],
    "capabilities": [
      "I CAN RUN"
    ]
  }
]``

var anyTemplate = {
content:{
 "sampleKey":{ paramsKey:"notAvailable"}
    }
}

j2j.run(anyTemplate, input);

This will fail- Cause i mentioned paramsKey in the template but didn't pass it from the run.. 

Thanks,
Sameer

**Comment by fastcodejava** [comment]
What exactly is the issue? The input is not even valid Json. 
What output are you getting and how is it different from your expectation?

**Comment by SameerSiddiqui** [comment]
The issue is- if we don't pass the third object containing ParamsKey, but we accidentally map it in our template. I get garbage value.

**Comment by fastcodejava** [comment]
I don't know what you mean by 

> garbage value . 

But I can put a `null` check for the `params`. I can do that once the current pull request is merged by @au2.

**Comment by SameerSiddiqui** [comment]
Let's say I have huge json payloads- with nested objects- In one of the array property which is a collection of objects- there are 30 keys, for each item in that array. I just need 25 keys- out of 30.  So i was wondering if we can have "copyKey" actionKey where i will just mention those 25 keys and they will  be mapped as it is. I am not sure, but by not mentioning any dataKey- those 5 will get excluded ? 

Thanks,
Sameer

**Comment by au2** [comment]
FIxed in 9b99ff0c22962a426040ff5ea6f86ee3b6eab4a5
