### ISSUE TITLE
Suggestion : Let's make default to accept functions-

### ISSUE THREAD

**Issue by SameerSiddiqui** [amida-tech/jsonapter#26]
As of now we can't pass function references in default action Key- If that would be possible- It would be great help..

Eg.

Let's say an incoming key "dateTime" has date and it's an optional key- If this key is not present in the input i still want to pass in the default date ( current dateTime ). I know i can achieve it using value, but default accepting functions will be clean.

`whenAuthorized : {dataKey:"whenAuthorized", default:utilHelper.getCurrentDate},`

The above is what i was looking for.

Thanks,
Sameer

**Comment by SameerSiddiqui** [comment]
@fastcodejava , can you do a PR on this one. 

Thanks,
Sameer

**Comment by fastcodejava** [comment]
@SameerSiddiqui It is possible to do this right now using [firstOf](https://github.com/amida-tech/jsonapter#firstOf).

**Comment by SameerSiddiqui** [comment]
Thanks- working fine with latest release!
