### ISSUE TITLE
Suggesstion- new actionKey - "copy" for as is mapping!

### ISSUE THREAD

**Issue by SameerSiddiqui** [amida-tech/jsonapter#27]
Lets say i have very big json payload- which i want to map it as it is ( may be someKeys or all) , means the output will have same keys as input and values.

eg: 

`input = {"a":"a","b":"b","c":"c","d":"a","e":"b","f":"c"}` .. and so forth... 

I want an output-

`output = {"a":"a","b":"b","c":"c","d":"a","e":"b","f":"c"}`

As of now- I have to  type each key individually and mention its dataKey. This is cumbersome..

I think we should have a new actionKey called  copy, or we can name it any thing meaningful. This action Key should always be an array and maps the sourceKeys as it is to output. 

So i should be able to just say 

copy:["a","b","c","d","e","f","g","h","i"]

and the template should be created as it is.. So basically this key will take the keys from the source as it is in a **collection** and map them to output as it is.

**Comment by fastcodejava** [comment]
Yeah, this would be useful!

**Comment by au2** [comment]
If you do not specify any action key the input will be returned as it is so I am not sure if we need this.  If you need it for clarity fine but I think the functionality is already there.  Maybe a specific example to clarify what it will look like helps.

**Comment by SameerSiddiqui** [comment]
Let's say I have huge json payloads- with nested objects- In one of the array property which is a collection of objects- there are 30 keys, for each item in that array. I just need 25 keys- out of 30.  So i was wondering if we can have "copyKey" actionKey where i will just mention those 25 keys and they will  be mapped as it is. I am not sure, but by not mentioning any dataKey- those 5 will get excluded ? 

Thanks,
Sameer

**Comment by au2** [comment]
OK.  I understand.  I think you can do that with lodash functions today; set value to be _.partial(_.pick, ['a', 'b', 'c', ...])).  Take look if that solves the problem.  We can add the key to be more clear as well.
