### ISSUE TITLE
Enhancement - Existswhen with string and object

### ISSUE THREAD

**Issue by fastcodejava** [amida-tech/jsonapter#28]
Right now it can only be a `function` which makes it verbose for simple conditions. We can accept a `string `which will mean if the value of the key is truthy. When it is an object we just check for each key with the value specified.
The opposite will hold true for `existsUnless`.

**Comment by au2** [comment]
I rather be consistent with lodash.  Please take a look at _.iteratee.  We can just call to that if existsWhen, existsUnless is not a function.

**Comment by fastcodejava** [comment]
That makes sense, I'll submit a PR soon.

**Comment by au2** [comment]
FIxed in 2df13819c6a8b357eae5242a59fd2b74b870f97c.
