### ISSUE TITLE
Enhancement - Existswhen/ExistsUnless with value

### ISSUE THREAD

**Issue by fastcodejava** [amida-tech/jsonapter#32]
Now we have made Existswhen/ExistsUnless a `string` which will mean if the value of the key is `truthy`. 
Sometimes we need check if the value itself is `truthy`.  E.g.

```

var valid_genders = {
     M: "Male",
     F: "Female"
}

var template = {
    content: {
        gender: {
            dataKey: 'gender'
        }
    },
    existsWhen: {
       value: valid_genders
   }
};

```

**Comment by fastcodejava** [comment]
This cannot be done as it would conflict with `existwhen` being an object. 
But this is such a nice idea, @au2  do you have an idea how to put this?

**Comment by au2** [comment]
I did not try but putting a 'value' function validator should do it I think.  Something like

var valid_genders = {
     M: "Male",
     F: "Female"
}

var template = {
    content: {
        gender: {
            value: function(input) {
              return valid_genders[input] ? input : null;
            },
            dataKey: 'gender'
        }
    }
};
