### ISSUE TITLE
Enhancement: access the value of the current element without using a function!

### ISSUE THREAD

**Issue by fastcodejava** [amida-tech/jsonapter#36]
This is the issue I'm trying to solve, given the input

    {product: "iProd"}

 I want to have this output:

    {
                        type: "product",
                        value: "iProd"
    }

the template 

      {
            dataKey: "product",
                content: {
                    type: {constant: 'product'},
                    value: {value: function (input) {return input;}}
                }
        }

How to access the value of the current element without using a **function**.
I'm thinking putting the `dataKey` with the dot (.) or introduce a different key?
@au2 what do you think?

**Comment by SameerSiddiqui** [comment]
Why don't you put your dataKey inside value        value: { dataKey:"product"}

**Comment by fastcodejava** [comment]
@SameerSiddiqui That is not always possible. What if products is an array of strings and I want that to be an area of object as shown below:

    {product: ["iPod", "iPad"]}

    [{
           type: "product",
           value: "iPod"
    },
    {
           type: "product",
           value: "iPad"
    }
    ]

**Comment by au2** [comment]
I am not sure why you want to avoid functions.  lodash has an identity function that you can use that is as easy as putting a string

value: _.identity

**Comment by fastcodejava** [comment]
​Yeah `identity` would definitely work but I was thinking of some syntactic sugar like : 

```
  {
        dataKey: "product",
            content: {
                type: {constant: 'product'},
                value: {}
            }
    }
```

**Comment by au2** [comment]
I do not have any problem using empty object `{}` to mean current element.  I peeked at the code and I think it should work that way anyway but I did not test.   It kinda goes through the hoops to get to that result though so if you want to make that explicit in the code (in evaluateValue probably), that makes sense.

**Comment by SameerSiddiqui** [comment]
I am not sure- I agree. I like explicit way of doing things! Just because we pass empty {}, and that IMPLIES that all values will be printed, seems ambiguous. Just my opinion. let's stick to just use _.identity

**Comment by fastcodejava** [comment]
@au2 it does work as you said. I put two test cases in the last PR. You should also document it somewhere , I didn't know how to put it.
