### ISSUE TITLE
I can't seem to be able to pass second parameter if value is a function reference- Unless i wrap the function inside another function and return-

### ISSUE THREAD

**Issue by SameerSiddiqui** [amida-tech/jsonapter#38]
```
timezone: {
	dataKey: "test.currentTimeZone",
	value: function(tz){
		return common.getTimezone(tz, secondParam);
	}
}
```

if you notice value has a wrapper function cause, my common.getTimeZone func needs another param- 

I shouldn't write a wrapper func on top of my common.getTimeZone func to just pass the second Param.

**Comment by fastcodejava** [comment]
Define 

```
function(tz){
		return common.getTimezone(tz, secondParam);
	}

```

as 

```
function(tz, params) {
		return common.getTimezone(tz, params);
	}
```

**Comment by SameerSiddiqui** [comment]
No, that is incorrect! I don't want to write a parent function on top of common.getTimeZone. You aren't getting my point!

**Comment by SameerSiddiqui** [comment]
@fastcodejava  - your params changes are able to accommodate what i was looking. Have you documented that some where. 

I can pass the second parameter value required by my function inside params and then reference it.

Thanks,
Sameer

**Comment by fastcodejava** [comment]
Yes it is : [value](https://github.com/amida-tech/jsonapter#value)

**Comment by SameerSiddiqui** [comment]
Thanks, That worked!
