### ISSUE TITLE
Make firstOf to work with arrayContent

### ISSUE THREAD

**Issue by SameerSiddiqui** [amida-tech/jsonapter#43]
Let's say i have people array-

The value for people array can come as a part of dataKey or it can come as a part of paramKey, depends on the situation- 

So as per the above useCase i should be able to map people array to another array and still be able to use firstOf like below-

```
var mappedPeople = {
    arrayContent: [{
        firstOf: [dataKey: "people", paramKey: "people"],
        content: {
            name: {
                dataKey: "firstName"
            }
        }
    }]
}
```

Or i should be able to do below

```
var mappedPeople = {
    arrayContent: [{
        dataKey: "people", 
        paramKey: "people"
        content: {
            name: {
                dataKey: "firstName"
            }
        }
    }]
}
```
So it should USE either dataKey or paramKey which ever is not undefined.

**Comment by fastcodejava** [comment]
What will be a sample input and output for this?

**Comment by SameerSiddiqui** [comment]
input: 
```
var peoples =[  
   {  
      "name":"Michael",
      "age":18
   },
   {  
      "name":"Andy",
      "age":30
   },
   {  
      "name":"Justin",
      "age":19
   }
]
```

Here is the output

var peoples =[  
   {  
      "name":"Michael",
   },
   {  
      "name":"Andy",
   },
   {  
      "name":"Justin",
   }
]
```

but in my case it doesn't matter what the input/output is- the deal is the incoming payload can be either supplied lie below-

`var r = j2j.run(myTemplate, peoples);`

or it can either come from params- as paramsKey- as given below.

```
var params = {};

params.peoples  = peoples;

var r = j2j.run(myTemplate, null, params);

```
So myTemplate should be clever enough to handle both inputs which ever is first undefined-

so i was trying to use firstOf within arrayContent.
