### ISSUE TITLE
existsWhen:"iAmFromParamKey"

### ISSUE THREAD

**Issue by SameerSiddiqui** [amida-tech/jsonapter#46]
existsWhen: was recently improved to directly access and work with keys. I am requesting one more enhancement. Where it should be clever enough to check on paramKey.

Thanks,
Sameer

**Comment by fastcodejava** [comment]
@SameerSiddiqui this is a good idea but if I call existsWhen with Params the test cases such as [these](https://github.com/amida-tech/jsonapter/blob/master/test/test-examples.js#L455) fail. 
It will work if it is a regular function but the wrapper function created by lodash [partialright ](https://lodash.com/docs/4.17.4#partialRight) is causing trouble. 
@au2 how would we handle this?

**Comment by fastcodejava** [comment]
I think this can be fixed by calling `function` with input first and if it is `false` then call it with `params`. 
I will submit a PR with this soon.
