### ISSUE TITLE
Improvement in existsWhen

### ISSUE THREAD

**Issue by SameerSiddiqui** [amida-tech/jsonapter#47]
`existsWhen: ['countMe', 'countMetoo','iMightCome'],
`

existsWhen can be an array but only works with AND statement. This is correct behavior, but can be made clever enough to work with OR.  i can pass a new  item like condition:AND or condition:OR  outside existsWhen and it should flip the behavior.

Thanks,
Sameer

**Comment by fastcodejava** [comment]
This is an excellent idea. I'm thinking of putting an **existsEither** tag. 
I don't know what @au2 will think about this.

**Comment by SameerSiddiqui** [comment]
Nice, Please can you make this change  ? and make a PR- existsEither:['IcanCome','iCanComeToo']

So basically it will be an OR between the items of array, and order matters for this array!

**Comment by fastcodejava** [comment]
@SameerSiddiqui same holds true for the `dataKey` if it is an array. 
Reason you want to use this probably because you have a template like this 

```
  {
	existsWhen: ['countMe', 'countMetoo','iMightCome'],
	content: {
		name: "myname",
		value: {dataKey: ['countMe',  'countMetoo', 'iMightCome'] }
	}
}
```
and your input is like this

```
     {
       'countMe': 'X',
       'countMetoo': 'Y',
       'iMightCome': 'Z'
     }
```
 with only one of the items can be present.
