### ISSUE TITLE
Unable to set a key with "DoT" in between

### ISSUE THREAD

**Issue by SameerSiddiqui** [amida-tech/jsonapter#5]
I am trying to generate a json object with a key that has "dot" in between-

SampleCode:

 content: {
        "Party.Preference": {
            content: {
                preference: {
                    arrayContent: [{..........

but my output JSON object is giving me nested like this

Party {
      Preference: {
        preference:[]
      }
}

Is there a way we can have a key with "DOT" and it doesn't gets nested-

Any advice will be helpful-

**Comment by SameerSiddiqui** [comment]
line 47 onwards: 
  
  var length = key.length;
                var firstChar = key.charAt(0);
                var lastChar = key.charAt(length -1);

                var setDotNotation = (firstChar === '[' && lastChar  === ']' && key.indexOf('.') != -1);

                if (setDotNotation){
                    key = key.substring(1,((length)-1));

                    r[key] = value;

                }else {
                    _.set(r, key, value);
                }

Hello guys, what about something like above? 

if the key passed is "[a.b]"
it will generate a key with a dot, instead of nesting it inside the object.  Please let me know if this solution will work up to the standards or some one has a better solution- I need to get this thing working soon.

**Comment by au2** [comment]
I added a template flag 'ignoreDeep'.  Specify it to be true on the same level as content

ignoreDeep: true,
content: {
"Party.Preference": {
...

**Comment by SameerSiddiqui** [comment]
awesome- works fine- 

Thanks,
Sameer
