### ISSUE TITLE
lets add indexKey:{}/  and also access to index in functions-

### ISSUE THREAD

**Issue by SameerSiddiqui** [amida-tech/jsonapter#54]
This will print index but lets make it available where i can access the index in functions.

**Comment by SameerSiddiqui** [comment]
This looks ok- but why it is 0 based. Nice to have an offset.

**Comment by SameerSiddiqui** [comment]
can you rename the key to arrayIndex instead of indexKey ?

**Comment by fastcodejava** [comment]
Good idea. Latest version has this feature.
