### ISSUE TITLE
Not Possible to generate array property from the source Array-

### ISSUE THREAD

**Issue by SameerSiddiqui** [amida-tech/jsonapter#63]
var sampleInput = [a: 1, b:2];

var sampleOutPut = {list: [{dest_a: 1}, {dest_b: 2}];

If you use assign or arrayContent. list will repetitive for each item in the array. Should be easy to reproduce using my sampleInput and sampleOutPut.

**Comment by SameerSiddiqui** [comment]
@fastcodejava , let me know if you need any help re-producing. I have a certain requirement where i have to show {price:"whatEver", productList:[{},{}]} <-- JSON.


productList is part of incoming JSON which is an Array. I wasn't able to do this mapping using jsonApter.

Thanks,
Sameer

**Comment by fastcodejava** [comment]
@SameerSiddiqui you are correct. Right now `jsonapter `always converts to an array if the input is an `array`. 
I am thinking of putting an output flag which can be object, string or array. 
If it is object it would convert output to an object even if input is an `array`. 
E.g this template will convert the input to :

        var template = {
             content: {
                 items: {
                     content: {
                         cost: {dataKey: 'price'}
                     }
                 }
             },
             output: 'object'
         };

input :
            [{
                 price: 10
             }, {
                 price: 20
             }, {
                 price: 30
             }]

output:

     {
       "items": [
      {
        "cost": 10
      },
      {
        "cost": 20
      },
      {
        "cost": 30
      }
      ]
     }

Right now `jsonapter` will convert to :

    [
      {
        "items": {
          "cost": 10
        }
      },
      {
        "items": {
          "cost": 20
        }
      },
      {
        "items": {
          "cost": 30
        }
      }
    ]

@au2 what do you think?
