### ISSUE TITLE
default not working with arrayContent-

### ISSUE THREAD

**Issue by SameerSiddiqui** [amida-tech/jsonapter#7]
var remoteCommandList= {
    arrayContent:[{
        single:true,
        default:[],
        dataKey:jsonave("$.body.Page.items.item"),
        value:commonTemplates.remoteCommand
    }]
};

Just quick challenge i encountered. When i pass default:[] inside an arrayContent and my dataKey is empty i still get my return array as null instead of empty array. like []

default:[] works within content but  doesn't seem to work within arrayContent.

It's not a biggy. I can still check for null at the client and assign empty array, but the framework should handle it.

Thanks for the help.

**Comment by au2** [comment]
This is not arrayContent specific and happens when input is an array.  It should be fixed now.
