### ISSUE TITLE
value: when assigned to a function reference should allow to pass a static param as fourth parameter-

### ISSUE THREAD

**Issue by SameerSiddiqui** [amida-tech/jsonapter#73]
function iAmTest(input,parent,params,staticValue){
return staticValue;
}

value: IAmTest, funcParams:[dataKey,parent,params,"IamStatic"]

something like above. Just an idea.

Thanks,
Sameeer

**Comment by fastcodejava** [comment]
I completely agree with this. The `value` function should take the `key` as well as arbitrary number of extra parameters. I'll get it done next week!
