### ISSUE TITLE
$unwind

### ISSUE THREAD

**Issue by amnotafraid** [amida-tech/jsonapter#76]
This is more of a question than an issue, but I don't know where to put it.  Thank you in advance for your help.

Is there a way to use jsonapter to 'unravel' arrays?  By 'unravel', I mean a way to flatten arrays within arrays.

As a simplified example, if I have this:
```
var input3 = {
  a1: [{
    x_outer: 1,
    y_outer: 2,
    z_outer: 3,
    a2: [{
      a_inner: 4,
      b_inner: 5,
      c_inner: 6
    }, {
      a_inner: 7,
      b_inner: 8,
      c_inner: 9
    }]  
  }]  
};
```
and I want this:
```
output = {
  stuff: [{
    x_new: 1,    // a1[0].x_outer
    a_new: 4     // a1[0].a2[0].a_inner
  },{
    x_new: 1,    // a1[0].x_outer
    a_new: 7     // a1[0].a2[1].a_inner
  }]
}
```
What I have so far is this template:
```
var template3 = {
  content: {
    stuff: {
      content: {
        x_new: {dataKey: jsonave('a1[:].x_outer')},
        a_new: {dataKey: jsonave('a1[:].a2[:].a_inner')}
      }
    }
  }
};
```
My output is this:
```
{
  "stuff": {
    "x_new": [
      1
    ],
    "a_new": [
      4,
      7
    ]
  }
}
```
I am stumped about how to get `x_new` and `a_new` in the same object, to get them in an array, and to get the `stuff` to repeat.  Is there a way to accomplish what I want?

**Comment by au2** [comment]
At this point the best I can think of now something like this.  Maybe another solution with simpler function can be found but I do not think you can do without a custom function somewhere in your template. 

var template= {
  content: {
    stuff: {
      content: {
        x_new: {dataKey: 'x_outer'},
        a_new: {
            dataKey: jsonave('a2[*].a_inner'),
        }
      },
      output: function(result) {
        var raw = result.map(function(r) {
            return r.a_new.map(function(p) {
                return {
                    a_new: p,
                    x_new: r.x_new
                }
            });
        });
        return _.flatten(raw);
      },
      dataKey: jsonave('a1[*]'),
    }
  }
};

**Comment by au2** [comment]
something similar to unwind looks to be a good thing to add to this library. i will take a look.

**Comment by amnotafraid** [comment]
Thank you VERY MUCH for your code.  It worked like I wanted it to.

When I was looking at the interface, it also crossed my mind that an `unwind` would be handy.  I will leave the issue open for that, but from my standpoint, I got the answer I needed.

**Comment by fastcodejava** [comment]
This is an excellent example of using the `output` tag. 
However, it can be simplified much with the following `template` which may seem more intuitive.
This uses the `value` tag with the `parent` as `parameter`.

```
{
    content: {
        stuff: {
            content: {
                temp: {
                    dataKey: jsonave('a2[:].a_inner'),
                    content: {
                        a_new: {},
                        x_new: function (input, parent, params) {
                            return parent.x_outer;
                        }
                    }
                }
            },
            output: function(result, input) {
                return result.temp;
            }
        }
    },
    dataKey: 'a1',
    single: true 
}

```
I get the same output:

```
{
  "stuff": [
    {
      "a_new": 4,
      "x_new": 1
    },
    {
      "a_new": 7,
      "x_new": 1
    }
  ]
}
```

Please let us know if you need any more help.

**Comment by fastcodejava** [comment]
The template can be much simplified. I don't know what I was thinking.

```
{
    content: {
        stuff: {
            dataKey: jsonave('a2[:].a_inner'),
            content: {
                a_new: {},
                x_new: function (input, parent, params) {
                    return parent.x_outer;
                }
            }
        }
    },
    dataKey: 'a1',
    single: true
};

```
Hope this helps.

**Comment by amnotafraid** [comment]
I like how much more simple this is if you can guarantee that the array a1 only has one element.  If I have this input:
```
var data4 = {
  a1: [{
    x_outer: 1,  y_outer: 2, z_outer: 3,  a2: [{
      a_inner: 4,  b_inner: 5,  c_inner: 6,
    }, {
      a_inner: 7, b_inner: 8,  c_inner: 9,
    }]
  }, {
    x_outer: 10, y_outer: 11, z_outer: 12, a2: [{
      a_inner: 13, b_inner: 14, c_inner: 15,
    }, {
      a_inner: 16, b_inner: 17, c_inner: 18,
    }]
  }]
};
```
I would want this output:
```
output = {
  stuff: [{
    x_new: 1,    // a1[0].x_outer
    a_new: 4    // a1[0].a2[0].a_inner
  },{
    x_new: 1,    // a1[0].x_outer
    a_new: 7     // a1[0].a2[1].a_inner
  },{
    x_new: 10,  // a1[1].x_outer
    a_new: 13   // a1[1].a2[0].a_inner
  },{
    x_new:10,   // a1[1].x_outer
    a_new: 16   // a1[1].a2[1].a_inner
  }]
}
```
I'll work on it and see if I can figure something better out.  I really appreciate your interest and help.

**Comment by fastcodejava** [comment]
If you remove the `single: true` you almost get the results except that it is in separate elements in an array. Now you need to do is to `flatten` the array. 
Shortly I will have `flatten: true`, `compact: true` etc for arrays. 
For now one can call the [flatten](https://lodash.com/docs/4.17.4#flatten) function.
Here is the complete template which gives you the desired result:

```
var template = {
    content: {
        stuff: {
            dataKey: 'a1',
            template: {
                dataKey: jsonave('a2[:].a_inner'),
                content: {
                    x_new: function (input, parent, params) {
                        return parent.x_outer;
                    },
                    a_new: {}
                }
            },
            output: _.flatten
        }
    }
};
```
