### ISSUE TITLE
Mapping array of strings to array of objects

### ISSUE THREAD

**Issue by ryanhomer** [amida-tech/jsonapter#83]
I've gone through all of the documentation and still cannot find a way to handle arrays of strings. Let's say I have the following data:

    { "someKey": [ "value1", "value2", "value3" ] }

and I would like to transform it to:

    {
      "someKey" : [
        { "id": "value1", "name": "value1" },
        { "id": "value2", "name": "value2" },
        { "id": "value3", "name": "value3" }
      ]
    }

Is this possible?

The issue I'm having is that I can't use `dataKey` to refer to the elements within the array like I do when I have an array of objects. I've also tried using `dataTransform` to no avail. Instead, I keep ending up with:

    {
      "someKey" : {
        "id":    [ "value1", "value2", "value3" ] ,
        "name":  [ "value1", "value2", "value3" ] 
      }
    }

Thanks in advance for any help on this.

**Comment by fastcodejava** [comment]
Thanks for playing with our library.
This can be easily done with the following template.

```
{
    dataKey: "someKey", content: {
	"id": {},
	"name": {}
}

```
No `dataTransform` is needed.
Note how the empty object `{}` produces the input value as it is. 
This may not be documented well but this is a nice little feature of this Library.

**Comment by ryanhomer** [comment]
Thanks! I didn't realize that you could use `dataKey` at the same level as `content`. Looking again at the examples, I now see how nested `dataKey` works and how `content` interacts with it.

Thanks for this amazing library. It's been a lifesaver.
