### ISSUE TITLE
JSON transformation without template ?

### ISSUE THREAD

**Issue by shaikshakeel** [amida-tech/jsonapter#85]
Hi,
I have an almost 3 keys in JSON(payload)

```
payload  = {
 aa_00 : 'value_1',
 aa_01 : 'value_2',
 aa_03 : 'value_3'
}
```

So, now I need to transform complete payload to as same but need to change only one key
output : 
```
payload = {
 aa_00 : 'value_4',
 aa_01 : 'value_2',
 aa_03 : 'value_3'
}

```
I don't want to include a template because in some cases I might have 150+ keys in JSON  and I want to change only two or three keys.

Is there any way to solve this problem?

**Comment by fastcodejava** [comment]
In this case you might not want to use Jsonapter. 
But if you do want to use you can take advantage of the `output` tag as shown below:


```
var template = {
       content : {
          aa_00 : {dataKey: "aa_00"},
       },
      output:  function(result, input) {
                        return _.merge({}, input, result);
                   }
}
```
Please let me know if you have any questions or comments.
