### ISSUE TITLE
JSON transformation, inject new object 

### ISSUE THREAD

**Issue by shaikshakeel** [amida-tech/jsonapter#86]
Thanks for such a good library. 

Here I have a question. 
for example, I have a JSON like this : 
```
{
    'aa_01': 'value_01',
    'aa_02' : 'value_02',
    'aa_03' : 'value_03',
    'aa_04' : 'value_04',
    'aa_05' : 'value_05'
}

```
Expected output : 
```
{
    'aa_01': 'value_01',
    {
       'aa_03' : 'value_03',
       'aa_04' : 'value_04',
       'aa_05' : 'value_05'
    },
    'aa_03' : 'value_03',
    'aa_04' : 'value_04',
    'aa_05' : 'value_05'
}
```

Here I need to convert JSON based on existWhen, 

when 'aa_02' key present, I need to inject one more JSON object into existed JSON, 

is it possible ??

**Comment by fastcodejava** [comment]
There are two issues here:

1. The output you have posted is not a valid Json
2. Jsonapter framework is not capable of injecting an object

However, you can always use the [output ](https://github.com/amida-tech/jsonapter#output) tag to return anything you like as shown below: 

```
            function(result, input, parent, params) {
                // return some other result
            }
```

**Comment by shaikshakeel** [comment]
okay, JSON should have key
here it goes valid JSON : 

```
{
	"aa_01": "value_01",
	"bb_02": {
		"aa_03": "value_03",
		"aa_04": "value_04",
		"aa_05": "value_05"
	},
	"aa_03": "value_03",
	"aa_04": "value_04",
	"aa_05": "value_05"
}
```
