### ISSUE TITLE
Cannot transform the data partially within a  template-

### ISSUE THREAD

**Issue by SameerSiddiqui** [amida-tech/jsonapter#9]
content: {
        PushNotificationAddress: {
           content: {
                deviceToken: {value:function(req){return req.body.deviceToken}},
                applicationId: {value:function(req){return req.body.applicationId}},
                deviceType: {value:function(req){return req.body.deviceType}},
                operatingSystem: {value: function(req){return req.body.deviceOSName}},
                osVersion: {value:function(req){return req.body.deviceOSVersion}},
                alias: {value:function(req){return req.body.aliasName}},
                notificationSourceId: {value:function(req){return utilHelper.findDeviceId(req)}},
                userId: {value:function(req){return utilHelper.getAccountIdFromRequest(req)}}
            }
        }
    }
};

if we notice my last two key's have different value within the req and rest of the object is constructed by req.body- 

If i place dataTransform at the top level return req.body then i can't assign values to last two keys-

if i use assign rule and break the object I am able to use 2 dataTransform above the content level  but the last two keys are appended outside the PushNotificationAddress object.

The above works but i have to write req.body for each key and then send req only to last two keys-

From the client side i can set up my req object where every thing stays in body- but i have to change it for each and every client method and that is a pain -

Any suggestions, can we have a merge rule ? or some thing along those lines ?

**Comment by austundag** [comment]
If I understand you correctly assign should work.  Try
content: {
PushNotificationAddress: {
assign: [{content: {
deviceToken: {dataKey:'deviceToken'},
applicationId: {dataKey: 'applicationId'},
deviceType: {dataKey: 'deviceType'},
operatingSystem: {dataKey: 'deviceOSName'},
osVersion: {dataKey: 'deviceOSVersion'},
alias: {dataKey: 'aliasName'}}, dataKey: 'body'}, 
{content: {
notificationSourceId: {value:function(req){return utilHelper.findDeviceId(req)}},
userId: {value:function(req){return utilHelper.getAccountIdFromRequest(req)}}
}}]
}
};

**Comment by SameerSiddiqui** [comment]
Nice- i didn't know that assign can be used within the objects also-

Worked perfectly- 

Thanks, 
Sameer
