### ISSUE TITLE
firstOf only works with null and not undefined for value

### ISSUE THREAD

**Issue by SameerSiddiqui** [amida-tech/jsonapter#91]
`var someTemplate = {
    firstOf: [
        {value: helper.findMyName},
        {paramKey: 'someThing'},
        {dataKey: 'req.body.someThing'}
    ]
};`

So in the above case, lets say the first Item in firstOf which is value returns undefined, the firstOf short circuits and doesn't fall back to second or third item in the list. This means that We have to explicitly return null every time if the first Item is a function in firstOf. 

Thanks,
Sameer

**Comment by au2** [comment]
fixed
